module.exports = [
    {
        "id": 0,
        "weight": 0,
        "count": false,
        "width": 1,
        "height": 1
    },
    {
        "id": 1,
        "name": "Права",
        "type": "id-card",
        "weight": 2,
        "image": "id-card.png",
        "count": false,
        "isActivate": true,
        "isShow": true,
        "width": 1,
        "height": 1,
        "playerItem": "license",
        "drop": "p_ld_id_card_01"
    },
    {
        "id": 2,
        "name": "Верх",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/top.png",
        "count": false,
        "inventory": true,
        "inventoryWidth": 6,
        "inventoryHeight": 1,
        "rightInventoryId": 0,
        "width": 2,
        "height": 2,
        "playerItem": "top",
        "drop": "prop_ld_tshirt_02",
        "hasNotInventoryInside": true
    },
    {
        "id": 3,
        "name": "Штаны",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/jeans.png",
        "inventory": true,
        "inventoryWidth": 6,
        "inventoryHeight": 1,
        "rightInventoryId": 1,
        "count": false,
        "width": 2,
        "height": 3,
        "playerItem": "leg",
        "drop": "prop_ld_jeans_02",
        "hasNotInventoryInside": true
    },
    {
        "id": 4,
        "name": "Обувь",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/sneaker.png",
        "count": false,
        "playerItem": "foot",
        "drop": "v_ret_ps_shoe_01",
        "width": 2,
        "height": 1
    },
    {
        "id": 5,
        "name": "Перчатки",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/gloves.png",
        "count": false,
        "playerItem": "gloves",
        "drop": "v_ret_ta_gloves",
        "width": 1,
        "height": 1
    },
    {
        "id": 6,
        "name": "Ключи",
        "type": "car-key",
        "weight": 2,
        "image": "car-key.png",
        "count": false,
        "drop": "p_car_keys_01",
        "isActivates": true,
        "width": 1,
        "height": 1
    },
    {
        "id": 7,
        "name": "Канистра",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/petrolcan.png",
        "count": false,
        "drop": "w_am_jerrycan",
        "weapon_hash": 883325847,
        "ammo": 0,
        "width": 2,
        "height": 2 
    },
    {
        "id": 8,
        "name": "Головной убор",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/hats.png",
        "count": false,
        "playerItem": "hat",
        "drop": "prop_cap_01",
        "width": 1,
        "height": 1
    },
    {
        "id": 9,
        "name": "Очки",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/glasses.png",
        "count": false,
        "playerItem": "glasses",
        "drop": "prop_cs_sol_glasses",
        "width": 1,
        "height": 1
    },
    {
        "id": 10,
        "name": "Серьги",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/ears.png",
        "count": false,
        "playerItem": "ears",
        "drop": "p_tmom_earrings_s",
        "width": 1,
        "height": 1
    },
    {
        "id": 11,
        "name": "Маска",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/mask.png",
        "playerItem": "masks",
        "count": false,
        "drop": "p_orleans_mask_s",
        "width": 1,
        "height": 1
    },
    {
        "id": 12,
        "name": "Аксессуар",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/accessorie.png",
        "playerItem": "accessories",
        "count": false,
        "drop": "p_watch_01",
        "width": 1,
        "height": 1
    },
    {
        "id": 13,
        "name": "Часы",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/watch.png",
        "playerItem": "watches",
        "count": false,
        "drop": "p_watch_01",
        "width": 1,
        "height": 1
    },
    {
        "id": 14,
        "name": "Браслет",
        "type": "clothes",
        "weight": 2,
        "image": "clothes/bracelet.png",
        "playerItem": "bracelets",
        "count": false,
        "drop": "p_watch_01",
        "width": 1,
        "height": 1
    },
    {
        "id": 15,
        "name": "Карта",
        "type": "card",
        "weight": 2,
        "image": "card.png",
        "count": false,
        "playerItem": "card",
        "drop": "prop_cs_credit_card",
        "width": 1,
        "height": 1
    },
    {
        "id": 16,
        "name": "Sprunk",
        "type": "drink",
        "weight": 2,
        "image": "food/sprunk.png",
        "count": false,
        "drop": "ng_proc_sodacan_01b",
        "isUse": true,
        "width": 1,
        "thirst": 15,
        "height": 1
    },
    {
        "id": 17,
        "name": "Coffie",
        "type": "drink",
        "weight": 2,
        "image": "food/coffie.png",
        "count": false,
        "drop": "p_ing_coffeecup_02",
        "isUse": true,
        "width": 1,
        "thirst": 20,
        "height": 1
    },
    {
        "id": 18,
        "name": "Телефон",
        "type": "phone",
        "weight": 2,
        "image": "phone.png",
        "count": false,
        "playerItem": "phone",
        "drop": "p_amb_phone_01",
        "width": 1,
        "height": 1

    },
    {
        "id": 19,
        "name": "Упаковка патрон",
        "weight": 2,
        "image": "bullet.png",
        "isStack": true,
        "maxStack": 3,
        "drop": "prop_gas_grenade",
        "weapon_hash": 2694266206,
        "ammo": 0,
        "width": 1,
        "height": 1
    },
    {
        "id": 20,
        "name": "Газ",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Bz-gas-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "prop_gas_grenade",
        "weapon_hash": 2694266206,
        "ammo": 0,
        "width": 1,
        "height": 1
    },
    {
        "id": 21,
        "name": "Advanced Rifle",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Advanced-rifle-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_ar_advancerifle",
        "weapon_hash": 2937143193,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 22,
        "name": "Advanced Rifle",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Assault-rifle-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_ar_assaultrifle",
        "weapon_hash": 3220176749,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 23,
        "name": "Advanced Rifle MK2",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Assault-rifle-mk2-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_ar_assaultrifle",
        "weapon_hash": 961495388,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 24,
        "name": "Advanced Shotgan",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Assault-shotgun-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sg_assaultshotgun",
        "weapon_hash": 3800352039,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 25,
        "name": "Advanced Shotgan",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Assault-shotgun-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sg_assaultshotgun",
        "weapon_hash": 3800352039,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 26,
        "name": "Assault-smg",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Assault-smg-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sb_assaultsmg",
        "weapon_hash": 4024951519,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 27,
        "name": "Bullpup",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Bullpup-rifle-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_ar_bullpuprifle",
        "weapon_hash": 2132975508,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 28,
        "name": "Bullpup2",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Bullpup-rifle-mk2-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_ar_bullpuprifle",
        "weapon_hash": 2228681469,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 29,
        "name": "Bullpup shotgun",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Bullpup-shotgun-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_ar_bullpuprifle",
        "weapon_hash": 2640438543,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 30,
        "name": "Carbine Rifle",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Carbine-rifle-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_ar_carbinerifle",
        "weapon_hash": 2210333304,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 31,
        "name": "Carbine Rifle2",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Carbine-rifle-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_ar_carbinerifle",
        "weapon_hash": 4208062921,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 32,
        "name": "Combat-MG",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Combat-mg-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_mg_combatmg",
        "weapon_hash": 2144741730,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 33,
        "name": "Combat-MG2",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Combat-mg-mk2-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_mg_combatmg",
        "weapon_hash": 3686625920,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 34,
        "name": "Combat PDW",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Combat-pdw-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_mg_combatmg",
        "weapon_hash": 171789620,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 35,
        "name": "Compact Rifle",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Compact-rifle-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_mg_combatmg",
        "weapon_hash": 1649403952,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 36,
        "name": "Gusenberg",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Gusenberg-sweeper-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sb_gusenberg",
        "weapon_hash": 1627465347,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 37,
        "name": "Heavy Shotgun",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Heavy-shotgun-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sg_heavyshotgun",
        "weapon_hash": 984333226,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 38,
        "name": "Marksman Pistol",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Marksman-pistol-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sg_sawnoff",
        "weapon_hash": 4019527611,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 39,
        "name": "Micro-SMG",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Micro-smg-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sb_microsmg",
        "weapon_hash": 324215364,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 40,
        "name": "Mini-SMG",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Mini-smg-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sb_microsmg",
        "weapon_hash": 3173288789,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 41,
        "name": "Pump Shotgun",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Pump-shotgun-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sg_pumpshotgun",
        "weapon_hash": 487013001,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 42,
        "name": "Pump Shotgun2",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Pump-shotgun-mk2-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sg_pumpshotgun",
        "weapon_hash": 1432025498,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 43,
        "name": "Sawed-off",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Sawed-off-shotgun-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sg_sawnoff",
        "weapon_hash": 2017895192,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 44,
        "name": "Sniper Rifle",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Sniper-rifle-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sr_sniperrifle",
        "weapon_hash": 100416529,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 45,
        "name": "Special Carbine",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Special-carbine-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_ar_specialcarbine",
        "weapon_hash": 2526821735,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 46,
        "name": "Special Carbine2",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Special-carbine-mk2-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_ar_specialcarbine",
        "weapon_hash": 3231910285,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 47,
        "name": "Ap pistol",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Appistol-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_pi_appistol",
        "weapon_hash": 584646201,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 48,
        "name": "Бита",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Baseball-bat-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_me_bat",
        "weapon_hash": 2508868239,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 49,
        "name": "Flare Gun",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Flaregun-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_pi_flaregun",
        "weapon_hash": 1198879012,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 50,
        "name": "Heavy Pistol",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Heavy-pistol-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_pi_heavypistol",
        "weapon_hash": 3523564046,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 51,
        "name": "Дубинка",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Nightstick-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_me_nightstick",
        "weapon_hash": 1737195953,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 52,
        "name": "Pistol 50",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Pistol.50-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_pi_pistol50",
        "weapon_hash": 2578377531,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 53,
        "name": "Pistol",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Pistol-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_pi_pistol",
        "weapon_hash": 453432689,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 54,
        "name": "Pistol MK2",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Pistol-mk2-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_pi_pistol",
        "weapon_hash": 3219281620,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 55,
        "name": "SNS Pistol",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Sns-pistol-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_pi_sns_pistol",
        "weapon_hash": 3218215474,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 56,
        "name": "Шокер",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Stungun-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_pi_stungun",
        "weapon_hash": 911657153,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 57,
        "name": "Vintage Pistol",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Vintage-pistol-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_pi_vintage_pistol",
        "weapon_hash": 137902532,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 58,
        "name": "Коробка",
        "weight": 2,
        "image": "box.png",
        "count": false,
        "isLies": true,
        "drop": "prop_box_ammo04a",
        "weapon_hash": 137902532,
        "isUse": true,
        "allHandSlot": true,
        "hasClothes": true,
        "ammo": 0,
        "width": 2,
        "height": 2
    },
    {
        "id": 59,
        "name": "Combat Pistol",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Combat-pistol-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_pi_combat_pistol",
        "weapon_hash": 1593441988,
        "ammo": 0,
        "width": 2,
        "height": 1
    },
    {
        "id": 60,
        "name": "SMG",
        "type": "weapon",
        "weight": 2,
        "image": "weapons/Smg-icon.png",
        "count": false,
        "isActivate": true,
        "drop": "w_sb_smg",
        "weapon_hash": 736523883,
        "ammo": 0,
        "width": 3,
        "height": 1
    },
    {
        "id": 61,
        "name": "Марихуана",
        "weight": 2,
        "image": "marijuana.png",
        "drop": "w_sb_smg",
        "isStack": true,
        "maxStack": 2,
        "isUse": true,
        "width": 1,
        "height": 1
    },
    {
        "id": 62,
        "name": "Косяк",
        "weight": 2,
        "image": "joint.png",
        "drop": "w_sb_smg",
        "isStack": true,
        "maxStack": 10,
        "isUse": true,
        "width": 1,
        "height": 1
    },
    {
        "id": 63,
        "name": "Сумка",
        "weight": 2,
        "image": "clothes/bag.png",
        "drop": "xm_prop_x17_bag_01d",
        "count": false,
        "inventory": true,
        "inventoryWidth": 4,
        "inventoryHeight": 5,
        "rightInventoryId": 2,
        "width": 2,
        "height": 2,
        "playerItem": "bag",
        "type": "bag",
    },
    {
        "id": 64,
        "name": "Воду",
        "weight": 2,
        "image": "food/water.png",
        "drop": "bkr_prop_coke_bottle_01a",
        "width": 1,
        "height": 1,
        "type": "drink",
        "count": false,
		"thirst": 20
    },
    {
        "id": 65,
        "name": "Молоко",
        "weight": 2,
        "image": "food/milk.png",
        "drop": "bkr_prop_coke_bottle_01a",
        "width": 1,
        "height": 1,
        "type": "drink",
        "count": false,
		"thirst": 30
    },
    {
        "id": 66,
        "name": "Энергетик",
        "weight": 2,
        "image": "food/can.png",
        "drop": "prop_energy_drink",
        "width": 1,
        "height": 1,
        "type": "drink",
        "count": false,
		"thirst": 50
    },	
    {
        "id": 67,
        "name": "Холодный чай",
        "weight": 2,
        "image": "food/tea.png",
        "drop": "prop_bar_drinkstraws",
        "width": 1,
        "height": 1,
        "type": "drink",
        "count": false,
		"thirst": 40
    },
    {
        "id": 68,
        "name": "Чизбургер",
        "weight": 2,
        "image": "food/food.png",
        "drop": "ng_proc_food_burg01a",
        "width": 1,
        "height": 1,
        "type": "food",
        "count": false,
		"satiety": 50
    },	
 {
        "id": 69,
        "name": "Кусок пиццы",
        "weight": 2,
        "image": "food/pizza.png",
        "drop": "v_ret_fh_pizza01",
        "width": 1,
        "height": 1,
        "type": "food",
        "count": false,
		"satiety": 40
    },		
 {
        "id": 70,
        "name": "Чипсы",
        "weight": 2,
        "image": "food/snack.png",
        "drop": "ng_proc_food_chips01c",
        "width": 1,
        "height": 1,
        "type": "food",
        "count": false,
		"satiety": 30
    },			
 {
        "id": 71,
        "name": "Хот-дог",
        "weight": 2,
        "image": "food/hotdog.png",
        "drop": "prop_cs_hotdog_01",
        "width": 1,
        "height": 1,
        "type": "food",
        "count": false,
		"satiety": 50
    },	
];